In [1]:
import joblib

gmm = joblib.load("./checkpoints/gmm_100_500iter_reg1-5/gmm_100_diag_reg1e-5.pkl")
scaler = joblib.load("./checkpoints/gmm_100_500iter_reg1-5/patch_scaler.pkl")

In [2]:
print("Components:", gmm.n_components)

Components: 100

In [3]:
from pathlib import Path

PROJECT_ROOT = Path("/projectnb/cs505am/students/hbbeth/DDIM/Sample-Adaptive-Diffusion-Steps")

DDR_ROOT = PROJECT_ROOT / "external" / "ddrm"
REF_RUN_DIR = DDR_ROOT / "exp" / "image_samples" / "IMAGENET 100 STRONG BLUR" / "run_imagenet100_k100_strongerblur"

eval_image_paths = sorted(list(REF_RUN_DIR.glob("y0_*.png")))

print("num eval degraded images:", len(eval_image_paths))
for p in eval_image_paths:
    print(p.name)

num eval degraded images: 100
y0_0.png
y0_1.png
y0_10.png
y0_11.png
y0_12.png
y0_13.png
y0_14.png
y0_15.png
y0_16.png
y0_17.png
y0_18.png
y0_19.png
y0_2.png
y0_20.png
y0_21.png
y0_22.png
y0_23.png
y0_24.png
y0_25.png
y0_26.png
y0_27.png
y0_28.png
y0_29.png
y0_3.png
y0_30.png
y0_31.png
y0_32.png
y0_33.png
y0_34.png
y0_35.png
y0_36.png
y0_37.png
y0_38.png
y0_39.png
y0_4.png
y0_40.png
y0_41.png
y0_42.png
y0_43.png
y0_44.png
y0_45.png
y0_46.png
y0_47.png
y0_48.png
y0_49.png
y0_5.png
y0_50.png
y0_51.png
y0_52.png
y0_53.png
y0_54.png
y0_55.png
y0_56.png
y0_57.png
y0_58.png
y0_59.png
y0_6.png
y0_60.png
y0_61.png
y0_62.png
y0_63.png
y0_64.png
y0_65.png
y0_66.png
y0_67.png
y0_68.png
y0_69.png
y0_7.png
y0_70.png
y0_71.png
y0_72.png
y0_73.png
y0_74.png
y0_75.png
y0_76.png
y0_77.png
y0_78.png
y0_79.png
y0_8.png
y0_80.png
y0_81.png
y0_82.png
y0_83.png
y0_84.png
y0_85.png
y0_86.png
y0_87.png
y0_88.png
y0_89.png
y0_9.png
y0_90.png
y0_91.png
y0_92.png
y0_93.png
y0_94.png
y0_95.png
y0_96.png
y0_97.png
y0_98.png
y0_99.png

In [1]:
kstar_labels = {
    "orig_0.png": 57,
    "orig_1.png": 46,
    "orig_2.png": 11,
    "orig_3.png": 42,
    "orig_4.png": 19,
    "orig_5.png": 30,
    "orig_6.png": 46,
    "orig_7.png": 38,
    "orig_8.png": 51,
    "orig_9.png": 28,
    "orig_10.png": 8,
    "orig_11.png": 31,
    "orig_12.png": 18,
    "orig_13.png": 24,
    "orig_14.png": 45,
    "orig_15.png": 36,
    "orig_16.png": 34,
    "orig_17.png": 53,
    "orig_18.png": 42,
    "orig_19.png": 53,
    "orig_20.png": 48,
    "orig_21.png": 45,
    "orig_22.png": 35,
    "orig_23.png": 35,
    "orig_24.png": 77,
    "orig_25.png": 5,
    "orig_26.png": 38,
    "orig_27.png": 30,
    "orig_28.png": 24,
    "orig_29.png": 21,
    "orig_30.png": 22,
    "orig_31.png": 8,
    "orig_32.png": 31,
    "orig_33.png": 34,
    "orig_34.png": 39,
    "orig_35.png": 14,
    "orig_36.png": 53,
    "orig_37.png": 5,
    "orig_38.png": 35,
    "orig_39.png": 33,
    "orig_40.png": 41,
    "orig_41.png": 34,
    "orig_42.png": 19,
    "orig_43.png": 34,
    "orig_44.png": 46,
    "orig_45.png": 17,
    "orig_46.png": 19,
    "orig_47.png": 51,
    "orig_48.png": 22,
    "orig_49.png": 51,
    "orig_50.png": 26,
    "orig_51.png": 15,
    "orig_52.png": 28,
    "orig_53.png": 51,
    "orig_54.png": 35,
    "orig_55.png": 29,
    "orig_56.png": 35,
    "orig_57.png": 72,
    "orig_58.png": 48,
    "orig_59.png": 24,
    "orig_60.png": 11,
    "orig_61.png": 34,
    "orig_62.png": 44,
    "orig_63.png": 44,
    "orig_64.png": 21,
    "orig_65.png": 48,
    "orig_66.png": 39,
    "orig_67.png": 36,
    "orig_68.png": 44,
    "orig_69.png": 5,
    "orig_70.png": 39,
    "orig_71.png": 39,
    "orig_72.png": 51,
    "orig_73.png": 32,
    "orig_74.png": 26,
    "orig_75.png": 35,
    "orig_76.png": 32,
    "orig_77.png": 23,
    "orig_78.png": 42,
    "orig_79.png": 51,
    "orig_80.png": 53,
    "orig_81.png": 35,
    "orig_82.png": 51,
    "orig_83.png": 53,
    "orig_84.png": 48,
    "orig_85.png": 42,
    "orig_86.png": 31,
    "orig_87.png": 41,
    "orig_88.png": 22,
    "orig_89.png": 34,
    "orig_90.png": 22,
    "orig_91.png": 11,
    "orig_92.png": 42,
    "orig_93.png": 26,
    "orig_94.png": 51,
    "orig_95.png": 45,
    "orig_96.png": 45,
    "orig_97.png": 41,
    "orig_98.png": 45,
    "orig_99.png": 5,
}

In [5]:
def load_grayscale_image(path, image_size=64):
    img = Image.open(path).convert("L")  # grayscale
    img = img.resize((image_size, image_size))
    arr = np.array(img).astype(np.float32) / 255.0
    return arr

def extract_patches(img, patch_size=8, stride=4):
    patches = []
    H, W = img.shape
    for i in range(0, H - patch_size + 1, stride):
        for j in range(0, W - patch_size + 1, stride):
            patch = img[i:i+patch_size, j:j+patch_size].reshape(-1)
            patches.append(patch)
    return np.array(patches, dtype=np.float32)

In [6]:
def image_complexity_nll(path, image_size=64, patch_size=8, stride=4):
    img = load_grayscale_image(path, image_size=image_size)
    patches = extract_patches(img, patch_size=patch_size, stride=stride)
    patches_scaled = scaler.transform(patches)

    log_probs = gmm.score_samples(patches_scaled)
    nll = -log_probs

    top_k = max(1, int(0.1 * len(nll)))
    sorted_nll = np.sort(nll)

    return {
        "mean_nll": float(np.mean(nll)),
        "std_nll": float(np.std(nll)),
        "max_nll": float(np.max(nll)),
        "median_nll": float(np.median(nll)),
        "p90_nll": float(np.percentile(nll, 90)),
        "top10_mean_nll": float(np.mean(sorted_nll[-top_k:])),
    }

In [7]:
import re
from PIL import Image
import numpy as np

def extract_image_idx(filename):
    # works for y0_0.png, orig_3.png, etc.
    m = re.search(r"_(\d+)\.png$", filename)
    if m is None:
        raise ValueError(f"Could not extract image index from {filename}")
    return int(m.group(1))

rows = []

for path in eval_image_paths:
    idx = extract_image_idx(path.name)
    orig_name = f"orig_{idx}.png"   # maps degraded image back to your k* labels

    stats = image_complexity_nll(path, image_size=64, patch_size=8, stride=4)

    rows.append({
        "image": path.name,          # now this will be y0_*.png
        "image_idx": idx,
        "mean_nll": stats["mean_nll"],
        "std_nll": stats["std_nll"],
        "max_nll": stats["max_nll"],
        "median_nll": stats["median_nll"],
        "p90_nll": stats["p90_nll"],
        "top10_mean_nll": stats["top10_mean_nll"],
        "kstar": kstar_labels[orig_name],
    })

rows

[{'image': 'y0_0.png',
  'image_idx': 0,
  'mean_nll': -35.569017511165704,
  'std_nll': 34.65413791549626,
  'max_nll': 46.27836157021355,
  'median_nll': -29.871644871531483,
  'p90_nll': 10.963242562606693,
  'top10_mean_nll': 20.20016604739192,
  'kstar': 57},
 {'image': 'y0_1.png',
  'image_idx': 1,
  'mean_nll': 2.891589812035385,
  'std_nll': 32.318491693319736,
  'max_nll': 56.369491039696456,
  'median_nll': 5.365288368014212,
  'p90_nll': 41.969183246834845,
  'top10_mean_nll': 48.257200757737884,
  'kstar': 46},
 {'image': 'y0_10.png',
  'image_idx': 10,
  'mean_nll': -12.3531355063228,
  'std_nll': 27.80920953656294,
  'max_nll': 60.33094912523994,
  'median_nll': -12.540016238924109,
  'p90_nll': 20.36824584342561,
  'top10_mean_nll': 39.61758641477962,
  'kstar': 8},
 {'image': 'y0_11.png',
  'image_idx': 11,
  'mean_nll': 1.5971006881020398,
  'std_nll': 26.7673124784685,
  'max_nll': 54.33923519058206,
  'median_nll': 2.325639649297352,
  'p90_nll': 28.970429633358357,
  'top10_mean_nll': 40.09712986128199,
  'kstar': 31},
 {'image': 'y0_12.png',
  'image_idx': 12,
  'mean_nll': 9.978365821075998,
  'std_nll': 24.192935792251454,
  'max_nll': 61.14903847375461,
  'median_nll': 9.53320556199286,
  'p90_nll': 44.915527562855516,
  'top10_mean_nll': 50.160387503835935,
  'kstar': 18},
 {'image': 'y0_13.png',
  'image_idx': 13,
  'mean_nll': -11.089703680971434,
  'std_nll': 40.621385995681315,
  'max_nll': 58.52436696119665,
  'median_nll': -2.287919676835725,
  'p90_nll': 36.15988405516575,
  'top10_mean_nll': 45.467715461484254,
  'kstar': 24},
 {'image': 'y0_14.png',
  'image_idx': 14,
  'mean_nll': -7.285421538413015,
  'std_nll': 36.450256294913075,
  'max_nll': 68.00347647077261,
  'median_nll': -2.0390327841506504,
  'p90_nll': 35.014411424225194,
  'top10_mean_nll': 44.2860260912451,
  'kstar': 45},
 {'image': 'y0_15.png',
  'image_idx': 15,
  'mean_nll': 18.552032824295214,
  'std_nll': 15.654329877064042,
  'max_nll': 55.66322916663178,
  'median_nll': 20.90804319623188,
  'p90_nll': 35.59316249253988,
  'top10_mean_nll': 41.47121687033268,
  'kstar': 36},
 {'image': 'y0_16.png',
  'image_idx': 16,
  'mean_nll': -9.931406613733854,
  'std_nll': 49.125002741827444,
  'max_nll': 77.14168597252235,
  'median_nll': -1.5847826270689218,
  'p90_nll': 51.21659397374959,
  'top10_mean_nll': 62.281199184156996,
  'kstar': 34},
 {'image': 'y0_17.png',
  'image_idx': 17,
  'mean_nll': -8.767659259814991,
  'std_nll': 24.578579279902634,
  'max_nll': 41.31331309981905,
  'median_nll': -8.91688202648748,
  'p90_nll': 22.157576966760136,
  'top10_mean_nll': 28.933796138541062,
  'kstar': 53},
 {'image': 'y0_18.png',
  'image_idx': 18,
  'mean_nll': -34.168468486990854,
  'std_nll': 37.434037609311915,
  'max_nll': 42.48896317850517,
  'median_nll': -26.583186883235665,
  'p90_nll': 14.08143453133747,
  'top10_mean_nll': 24.596531735629426,
  'kstar': 42},
 {'image': 'y0_19.png',
  'image_idx': 19,
  'mean_nll': -30.04754242264282,
  'std_nll': 38.17901971487822,
  'max_nll': 51.5605191646343,
  'median_nll': -28.042096161986127,
  'p90_nll': 21.019150893515924,
  'top10_mean_nll': 31.553630388875675,
  'kstar': 53},
 {'image': 'y0_2.png',
  'image_idx': 2,
  'mean_nll': -9.674577569164242,
  'std_nll': 24.036398771027013,
  'max_nll': 36.82222192594282,
  'median_nll': -8.926544418693945,
  'p90_nll': 19.96240402443157,
  'top10_mean_nll': 25.831681996430337,
  'kstar': 11},
 {'image': 'y0_20.png',
  'image_idx': 20,
  'mean_nll': 9.36257114374759,
  'std_nll': 37.74062048431519,
  'max_nll': 68.15014739846536,
  'median_nll': 18.452455192424257,
  'p90_nll': 44.634047377550814,
  'top10_mean_nll': 51.55095378804766,
  'kstar': 48},
 {'image': 'y0_21.png',
  'image_idx': 21,
  'mean_nll': 2.625019927797179,
  'std_nll': 28.88488042372136,
  'max_nll': 62.00875639661297,
  'median_nll': 6.487306924177516,
  'p90_nll': 36.81628532176914,
  'top10_mean_nll': 46.05800669121209,
  'kstar': 45},
 {'image': 'y0_22.png',
  'image_idx': 22,
  'mean_nll': -15.051535288202803,
  'std_nll': 35.03262931741087,
  'max_nll': 63.732613484213665,
  'median_nll': -12.117463635774016,
  'p90_nll': 27.80783908833601,
  'top10_mean_nll': 37.84244381478227,
  'kstar': 35},
 {'image': 'y0_23.png',
  'image_idx': 23,
  'mean_nll': 3.1663196428818874,
  'std_nll': 29.484279942316146,
  'max_nll': 67.19450165303154,
  'median_nll': 3.010196071466019,
  'p90_nll': 43.92025271886568,
  'top10_mean_nll': 50.81055255200449,
  'kstar': 35},
 {'image': 'y0_24.png',
  'image_idx': 24,
  'mean_nll': -31.688626398141945,
  'std_nll': 25.411419529788915,
  'max_nll': 33.777401775906256,
  'median_nll': -26.158357028820237,
  'p90_nll': 0.17713957621148377,
  'top10_mean_nll': 13.779472699599706,
  'kstar': 77},
 {'image': 'y0_25.png',
  'image_idx': 25,
  'mean_nll': -20.968478688803533,
  'std_nll': 22.4376737739283,
  'max_nll': 24.06401242135789,
  'median_nll': -15.702231267035302,
  'p90_nll': 4.256595936226225,
  'top10_mean_nll': 11.79618791751335,
  'kstar': 5},
 {'image': 'y0_26.png',
  'image_idx': 26,
  'mean_nll': 3.918649810527844,
  'std_nll': 33.94506198561439,
  'max_nll': 67.42676362089792,
  'median_nll': 4.253517840940077,
  'p90_nll': 47.5679564970459,
  'top10_mean_nll': 57.05970300975286,
  'kstar': 38},
 {'image': 'y0_27.png',
  'image_idx': 27,
  'mean_nll': -4.362747169989709,
  'std_nll': 30.259765913068758,
  'max_nll': 53.16030921483836,
  'median_nll': 2.3877304849741163,
  'p90_nll': 28.631626509667587,
  'top10_mean_nll': 39.73930178907171,
  'kstar': 30},
 {'image': 'y0_28.png',
  'image_idx': 28,
  'mean_nll': -4.455678594517713,
  'std_nll': 20.252608611389306,
  'max_nll': 43.456142574526986,
  'median_nll': -5.547518062447441,
  'p90_nll': 20.621514579854978,
  'top10_mean_nll': 30.445184686428934,
  'kstar': 24},
 {'image': 'y0_29.png',
  'image_idx': 29,
  'mean_nll': 7.502621011098392,
  'std_nll': 21.195870473627238,
  'max_nll': 48.65403238403321,
  'median_nll': 9.898882931032052,
  'p90_nll': 31.70940294778771,
  'top10_mean_nll': 35.670787374864915,
  'kstar': 21},
 {'image': 'y0_3.png',
  'image_idx': 3,
  'mean_nll': 6.066140246809797,
  'std_nll': 28.70027391848414,
  'max_nll': 59.175567264157266,
  'median_nll': 12.631083625632684,
  'p90_nll': 35.936828333402225,
  'top10_mean_nll': 46.81569840427548,
  'kstar': 42},
 {'image': 'y0_30.png',
  'image_idx': 30,
  'mean_nll': -3.5577447544118073,
  'std_nll': 28.646388376977473,
  'max_nll': 53.556309753322964,
  'median_nll': -3.481418096731459,
  'p90_nll': 29.84755094721666,
  'top10_mean_nll': 40.43862971894505,
  'kstar': 22},
 {'image': 'y0_31.png',
  'image_idx': 31,
  'mean_nll': -2.541437715384009,
  'std_nll': 27.73602931471443,
  'max_nll': 54.199011735462534,
  'median_nll': 5.394598450009664,
  'p90_nll': 25.808411677516787,
  'top10_mean_nll': 33.796206252565256,
  'kstar': 8},
 {'image': 'y0_32.png',
  'image_idx': 32,
  'mean_nll': 19.1888303513377,
  'std_nll': 18.687171516763396,
  'max_nll': 57.300549753090394,
  'median_nll': 21.60367689310671,
  'p90_nll': 39.24153345518466,
  'top10_mean_nll': 45.4607102584562,
  'kstar': 31},
 {'image': 'y0_33.png',
  'image_idx': 33,
  'mean_nll': -24.39517574284421,
  'std_nll': 36.78899758365284,
  'max_nll': 44.3267295020412,
  'median_nll': -11.709590453378546,
  'p90_nll': 15.945693853587683,
  'top10_mean_nll': 22.464290187102907,
  'kstar': 34},
 {'image': 'y0_34.png',
  'image_idx': 34,
  'mean_nll': 1.7357779154083315,
  'std_nll': 39.79566658313078,
  'max_nll': 88.3458746392126,
  'median_nll': 5.568834214234716,
  'p90_nll': 49.51184717047595,
  'top10_mean_nll': 63.77032830120783,
  'kstar': 39},
 {'image': 'y0_35.png',
  'image_idx': 35,
  'mean_nll': 0.1844105915192132,
  'std_nll': 24.638471133019802,
  'max_nll': 51.72149186704719,
  'median_nll': 4.76328436087904,
  'p90_nll': 26.101939879944624,
  'top10_mean_nll': 35.27137764127612,
  'kstar': 14},
 {'image': 'y0_36.png',
  'image_idx': 36,
  'mean_nll': 0.5064123547525003,
  'std_nll': 37.52604420852219,
  'max_nll': 75.80321050167633,
  'median_nll': 2.7407026137962434,
  'p90_nll': 49.27630555784552,
  'top10_mean_nll': 59.165381947020826,
  'kstar': 53},
 {'image': 'y0_37.png',
  'image_idx': 37,
  'mean_nll': -21.044187995044012,
  'std_nll': 27.872859289123372,
  'max_nll': 30.802008373210093,
  'median_nll': -22.709584100834185,
  'p90_nll': 18.299901862742193,
  'top10_mean_nll': 23.810530108329303,
  'kstar': 5},
 {'image': 'y0_38.png',
  'image_idx': 38,
  'mean_nll': 6.270015965698671,
  'std_nll': 28.330374852877505,
  'max_nll': 78.26005999928438,
  'median_nll': 9.736427196299783,
  'p90_nll': 41.89271105791835,
  'top10_mean_nll': 53.98514577331202,
  'kstar': 35},
 {'image': 'y0_39.png',
  'image_idx': 39,
  'mean_nll': -8.75189859795723,
  'std_nll': 35.93988924223231,
  'max_nll': 53.35813550265359,
  'median_nll': -0.5386594974713199,
  'p90_nll': 29.09945471704343,
  'top10_mean_nll': 38.23592803905174,
  'kstar': 33},
 {'image': 'y0_4.png',
  'image_idx': 4,
  'mean_nll': -16.556940447496817,
  'std_nll': 30.052984259453275,
  'max_nll': 34.08599537596425,
  'median_nll': -13.366831100569032,
  'p90_nll': 18.153134854708952,
  'top10_mean_nll': 24.241277239037547,
  'kstar': 19},
 {'image': 'y0_40.png',
  'image_idx': 40,
  'mean_nll': 27.212003500598463,
  'std_nll': 23.35079559803034,
  'max_nll': 68.25040963960515,
  'median_nll': 31.25496771202496,
  'p90_nll': 48.43252193035381,
  'top10_mean_nll': 55.89368598982125,
  'kstar': 41},
 {'image': 'y0_41.png',
  'image_idx': 41,
  'mean_nll': 2.826506396529634,
  'std_nll': 24.10109067991123,
  'max_nll': 69.34771676739193,
  'median_nll': 2.7302931195881897,
  'p90_nll': 31.254970909688222,
  'top10_mean_nll': 49.44612287560856,
  'kstar': 34},
 {'image': 'y0_42.png',
  'image_idx': 42,
  'mean_nll': 0.9187582550370778,
  'std_nll': 31.781395486997493,
  'max_nll': 87.55645205192083,
  'median_nll': 5.528762352693148,
  'p90_nll': 35.71587691568612,
  'top10_mean_nll': 49.228133424506495,
  'kstar': 19},
 {'image': 'y0_43.png',
  'image_idx': 43,
  'mean_nll': 13.709405876853427,
  'std_nll': 24.247555200232192,
  'max_nll': 70.24453651344254,
  'median_nll': 15.53326012585848,
  'p90_nll': 42.88608413771574,
  'top10_mean_nll': 53.42426104858032,
  'kstar': 34},
 {'image': 'y0_44.png',
  'image_idx': 44,
  'mean_nll': -7.2842311706116,
  'std_nll': 37.069818665306094,
  'max_nll': 50.546430325245204,
  'median_nll': 5.552990109058913,
  'p90_nll': 28.977944271997696,
  'top10_mean_nll': 37.06573171568722,
  'kstar': 46},
 {'image': 'y0_45.png',
  'image_idx': 45,
  'mean_nll': -18.925142814901314,
  'std_nll': 41.736428719866865,
  'max_nll': 60.30764732614889,
  'median_nll': -4.214716216852581,
  'p90_nll': 24.571702735674567,
  'top10_mean_nll': 36.77273564883067,
  'kstar': 17},
 {'image': 'y0_46.png',
  'image_idx': 46,
  'mean_nll': -28.642925094577876,
  'std_nll': 41.90643989968955,
  'max_nll': 45.55992807188745,
  'median_nll': -19.873240290997376,
  'p90_nll': 25.06241188562162,
  'top10_mean_nll': 33.651603119504664,
  'kstar': 19},
 {'image': 'y0_47.png',
  'image_idx': 47,
  'mean_nll': -17.761200807385922,
  'std_nll': 38.55375843289832,
  'max_nll': 48.84438655281885,
  'median_nll': -14.08486683445582,
  'p90_nll': 27.439712711753803,
  'top10_mean_nll': 36.793659578958575,
  'kstar': 51},
 {'image': 'y0_48.png',
  'image_idx': 48,
  'mean_nll': 2.250015808778761,
  'std_nll': 34.607069706987204,
  'max_nll': 77.8668181590391,
  'median_nll': 7.942903971366082,
  'p90_nll': 43.93237405954972,
  'top10_mean_nll': 56.38105788733556,
  'kstar': 22},
 {'image': 'y0_49.png',
  'image_idx': 49,
  'mean_nll': -6.735737313062868,
  'std_nll': 35.29020496790151,
  'max_nll': 52.72124028712217,
  'median_nll': 0.6726682090584388,
  'p90_nll': 34.67012256334386,
  'top10_mean_nll': 42.817951931236266,
  'kstar': 51},
 {'image': 'y0_5.png',
  'image_idx': 5,
  'mean_nll': -8.667311096656851,
  'std_nll': 43.12140707009997,
  'max_nll': 62.34228621556519,
  'median_nll': -0.028325009804689986,
  'p90_nll': 43.06752471564198,
  'top10_mean_nll': 50.22048574565229,
  'kstar': 30},
 {'image': 'y0_50.png',
  'image_idx': 50,
  'mean_nll': 5.408307605393123,
  'std_nll': 23.588848046132078,
  'max_nll': 60.13324833490529,
  'median_nll': 6.465532729721018,
  'p90_nll': 34.1832743459736,
  'top10_mean_nll': 44.77960384256563,
  'kstar': 26},
 {'image': 'y0_51.png',
  'image_idx': 51,
  'mean_nll': -17.741321032038538,
  'std_nll': 40.03537270929414,
  'max_nll': 53.46098408853115,
  'median_nll': -7.848809146781712,
  'p90_nll': 31.37172157402132,
  'top10_mean_nll': 41.24826880880202,
  'kstar': 15},
 {'image': 'y0_52.png',
  'image_idx': 52,
  'mean_nll': -16.384316668019395,
  'std_nll': 31.30417277871512,
  'max_nll': 56.10914631791012,
  'median_nll': -17.79022453622801,
  'p90_nll': 26.680026013106897,
  'top10_mean_nll': 39.19685879020777,
  'kstar': 28},
 {'image': 'y0_53.png',
  'image_idx': 53,
  'mean_nll': 9.865964751453653,
  'std_nll': 26.56071395336189,
  'max_nll': 67.67266217261474,
  'median_nll': 8.57698238108602,
  'p90_nll': 46.09813266236248,
  'top10_mean_nll': 52.579784839397846,
  'kstar': 51},
 {'image': 'y0_54.png',
  'image_idx': 54,
  'mean_nll': 0.9223822445254695,
  'std_nll': 25.63657734902432,
  'max_nll': 59.725498990597394,
  'median_nll': 2.7484405750040715,
  'p90_nll': 30.661351812284344,
  'top10_mean_nll': 41.82248033456085,
  'kstar': 35},
 {'image': 'y0_55.png',
  'image_idx': 55,
  'mean_nll': 5.304297630610656,
  'std_nll': 25.971266574965565,
  'max_nll': 68.71849409563848,
  'median_nll': 6.242747380152733,
  'p90_nll': 38.280676136453,
  'top10_mean_nll': 45.98750661267976,
  'kstar': 29},
 {'image': 'y0_56.png',
  'image_idx': 56,
  'mean_nll': -30.29666205203643,
  'std_nll': 36.12036380438014,
  'max_nll': 53.25580378101365,
  'median_nll': -33.110911684896294,
  'p90_nll': 20.657480888023862,
  'top10_mean_nll': 30.876093767737874,
  'kstar': 35},
 {'image': 'y0_57.png',
  'image_idx': 57,
  'mean_nll': -11.335839769982785,
  'std_nll': 35.254226264754884,
  'max_nll': 42.702503898822876,
  'median_nll': -5.976592019902221,
  'p90_nll': 27.771687636404533,
  'top10_mean_nll': 34.17453367334126,
  'kstar': 72},
 {'image': 'y0_58.png',
  'image_idx': 58,
  'mean_nll': -1.4452123718052952,
  'std_nll': 31.529270681861284,
  'max_nll': 71.34441060150597,
  'median_nll': -3.3188622748273415,
  'p90_nll': 40.80511715979569,
  'top10_mean_nll': 55.561637851940105,
  'kstar': 48},
 {'image': 'y0_59.png',
  'image_idx': 59,
  'mean_nll': -48.67609834423238,
  'std_nll': 39.083594724167305,
  'max_nll': 40.923492360976,
  'median_nll': -63.97393575410908,
  'p90_nll': 16.08368709844134,
  'top10_mean_nll': 24.231671312378783,
  'kstar': 24},
 {'image': 'y0_6.png',
  'image_idx': 6,
  'mean_nll': -47.233562662129,
  'std_nll': 37.601109166968705,
  'max_nll': 43.28416961750001,
  'median_nll': -65.38067706338339,
  'p90_nll': 14.329760003156746,
  'top10_mean_nll': 20.950732283175352,
  'kstar': 46},
 {'image': 'y0_60.png',
  'image_idx': 60,
  'mean_nll': -2.4125876857943784,
  'std_nll': 39.109064301651614,
  'max_nll': 56.35182446267388,
  'median_nll': 13.812382203934224,
  'p90_nll': 40.21724871064233,
  'top10_mean_nll': 45.84975487041534,
  'kstar': 11},
 {'image': 'y0_61.png',
  'image_idx': 61,
  'mean_nll': -26.752362601948764,
  'std_nll': 40.41441516623542,
  'max_nll': 55.70550496978362,
  'median_nll': -12.373429695027678,
  'p90_nll': 21.256992566128584,
  'top10_mean_nll': 35.186777045960376,
  'kstar': 34},
 {'image': 'y0_62.png',
  'image_idx': 62,
  'mean_nll': -22.935938146079636,
  'std_nll': 37.724576297632346,
  'max_nll': 43.35623658733969,
  'median_nll': -20.50051251622911,
  'p90_nll': 30.339900929127285,
  'top10_mean_nll': 35.81195610678636,
  'kstar': 44},
 {'image': 'y0_63.png',
  'image_idx': 63,
  'mean_nll': -14.903108700713394,
  'std_nll': 48.18573481100903,
  'max_nll': 62.4279481925707,
  'median_nll': -14.00219312070852,
  'p90_nll': 47.43941237413006,
  'top10_mean_nll': 55.18279697866557,
  'kstar': 44},
 {'image': 'y0_64.png',
  'image_idx': 64,
  'mean_nll': 13.146714707721772,
  'std_nll': 26.917308842504447,
  'max_nll': 61.39569836444608,
  'median_nll': 17.743372353692845,
  'p90_nll': 40.46782254290436,
  'top10_mean_nll': 46.26565545277411,
  'kstar': 21},
 {'image': 'y0_65.png',
  'image_idx': 65,
  'mean_nll': 17.02167354947984,
  'std_nll': 27.100037143554673,
  'max_nll': 69.1562976235738,
  'median_nll': 19.351394189672593,
  'p90_nll': 48.57296662735879,
  'top10_mean_nll': 56.77933202798254,
  'kstar': 48},
 {'image': 'y0_66.png',
  'image_idx': 66,
  'mean_nll': -9.516894180071379,
  'std_nll': 31.96737405135533,
  'max_nll': 51.79673898291072,
  'median_nll': -4.553956173192596,
  'p90_nll': 25.367314040316984,
  'top10_mean_nll': 34.59227289847207,
  'kstar': 39},
 {'image': 'y0_67.png',
  'image_idx': 67,
  'mean_nll': -31.66975021805768,
  'std_nll': 40.14185918370712,
  'max_nll': 50.42589932843887,
  'median_nll': -28.092915330877585,
  'p90_nll': 21.280432276054167,
  'top10_mean_nll': 32.014424511271436,
  'kstar': 36},
 {'image': 'y0_68.png',
  'image_idx': 68,
  'mean_nll': 1.1559156080710717,
  'std_nll': 21.851543050005834,
  'max_nll': 46.35976452158411,
  'median_nll': -0.46684016061362754,
  'p90_nll': 29.226033050288898,
  'top10_mean_nll': 39.36978348194368,
  'kstar': 44},
 {'image': 'y0_69.png',
  'image_idx': 69,
  'mean_nll': -40.80443976880991,
  'std_nll': 25.241330750496406,
  'max_nll': 25.2123269391888,
  'median_nll': -44.831602806636276,
  'p90_nll': -10.64313363566929,
  'top10_mean_nll': 3.6073107971433647,
  'kstar': 5},
 {'image': 'y0_7.png',
  'image_idx': 7,
  'mean_nll': -2.405707758787042,
  'std_nll': 24.936817905968322,
  'max_nll': 57.38049102385628,
  'median_nll': -3.2684939160263107,
  'p90_nll': 29.425688501092555,
  'top10_mean_nll': 38.997163831672346,
  'kstar': 38},
 {'image': 'y0_70.png',
  'image_idx': 70,
  'mean_nll': -13.670839727835451,
  'std_nll': 13.917395794037018,
  'max_nll': 16.779464221575953,
  'median_nll': -12.537998450114305,
  'p90_nll': 2.8801338262560323,
  'top10_mean_nll': 9.159013272171551,
  'kstar': 39},
 {'image': 'y0_71.png',
  'image_idx': 71,
  'mean_nll': 20.5238626305015,
  'std_nll': 22.057566860258603,
  'max_nll': 62.63179647715966,
  'median_nll': 22.62746332913221,
  'p90_nll': 45.567471545676824,
  'top10_mean_nll': 52.07508554767114,
  'kstar': 39},
 {'image': 'y0_72.png',
  'image_idx': 72,
  'mean_nll': -15.781315610779792,
  'std_nll': 41.278277501850475,
  'max_nll': 67.46677818132774,
  'median_nll': -12.645126534034452,
  'p90_nll': 35.6568062470535,
  'top10_mean_nll': 46.36180193622748,
  'kstar': 51},
 {'image': 'y0_73.png',
  'image_idx': 73,
  'mean_nll': -37.516792609621966,
  'std_nll': 36.5567911087807,
  'max_nll': 44.0998518947503,
  'median_nll': -49.0618435136475,
  'p90_nll': 15.734166128686194,
  'top10_mean_nll': 27.09897040107616,
  'kstar': 32},
 {'image': 'y0_74.png',
  'image_idx': 74,
  'mean_nll': -1.5987276817258818,
  'std_nll': 33.09930621046155,
  'max_nll': 54.074870465512845,
  'median_nll': 5.012909011653687,
  'p90_nll': 32.48932034759135,
  'top10_mean_nll': 39.20065789619085,
  'kstar': 26},
 {'image': 'y0_75.png',
  'image_idx': 75,
  'mean_nll': 3.7780876805461445,
  'std_nll': 30.691301403472128,
  'max_nll': 52.30795813640905,
  'median_nll': 9.191220194628245,
  'p90_nll': 40.57624036504622,
  'top10_mean_nll': 44.87999963999345,
  'kstar': 35},
 {'image': 'y0_76.png',
  'image_idx': 76,
  'mean_nll': 24.52458705291237,
  'std_nll': 26.23889193667743,
  'max_nll': 72.91612256837259,
  'median_nll': 28.455889172665827,
  'p90_nll': 57.04318484125138,
  'top10_mean_nll': 62.54604022272586,
  'kstar': 32},
 {'image': 'y0_77.png',
  'image_idx': 77,
  'mean_nll': -18.984309094307797,
  'std_nll': 47.18062790853814,

In [8]:
import pandas as pd

df = pd.DataFrame(rows).sort_values("image").reset_index(drop=True)
df.to_csv("gmm_results_imgnet100_strongerblur.csv", index=False)
print("saved gmm_results_imgnet100_strongerblur.csv")
df

saved gmm_results_imgnet100_strongerblur.csv

,image,image_idx,mean_nll,std_nll,max_nll,median_nll,p90_nll,top10_mean_nll,kstar
0,y0_0.png,0,-35.569018,34.654138,46.278362,-29.871645,10.963243,20.200166,57
1,y0_1.png,1,2.891590,32.318492,56.369491,5.365288,41.969183,48.257201,46
2,y0_10.png,10,-12.353136,27.809210,60.330949,-12.540016,20.368246,39.617586,8
3,y0_11.png,11,1.597101,26.767312,54.339235,2.325640,28.970430,40.097130,31
4,y0_12.png,12,9.978366,24.192936,61.149038,9.533206,44.915528,50.160388,18
...,...,...,...,...,...,...,...,...,...
95,y0_95.png,95,16.624096,28.544132,62.431881,22.529280,46.028165,53.421239,45
96,y0_96.png,96,-1.757263,41.749042,68.965516,10.728576,42.173386,49.726142,45
97,y0_97.png,97,6.486147,30.649733,70.172862,12.051853,38.844075,51.599652,41
98,y0_98.png,98,-3.902189,28.810399,58.050335,1.072423,28.299559,35.611122,45
99,y0_99.png,99,-0.464256,32.899658,61.120752,1.811348,42.934010,51.504386,5

In [9]:
from scipy.stats import pearsonr, spearmanr

features = ["mean_nll", "std_nll", "max_nll", "median_nll", "p90_nll", "top10_mean_nll"]

for feat in features:
    x = df[feat].values
    y = df["kstar"].values

    pearson_r, pearson_p = pearsonr(x, y)
    spearman_r, spearman_p = spearmanr(x, y)

    print(f"{feat} vs k*")
    print(f"  Pearson:  r={pearson_r:.4f}, p={pearson_p:.4f}")
    print(f"  Spearman: r={spearman_r:.4f}, p={spearman_p:.4f}")
    print()

mean_nll vs k*
  Pearson:  r=0.0155, p=0.8780
  Spearman: r=0.0241, p=0.8118

std_nll vs k*
  Pearson:  r=0.1586, p=0.1150
  Spearman: r=0.2002, p=0.0458

max_nll vs k*
  Pearson:  r=0.1319, p=0.1908
  Spearman: r=0.1326, p=0.1885

median_nll vs k*
  Pearson:  r=0.0247, p=0.8072
  Spearman: r=0.0325, p=0.7486

p90_nll vs k*
  Pearson:  r=0.1318, p=0.1912
  Spearman: r=0.1655, p=0.0998

top10_mean_nll vs k*
  Pearson:  r=0.1243, p=0.2178
  Spearman: r=0.1580, p=0.1163

In [10]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr

features = ["mean_nll", "std_nll", "max_nll", "median_nll", "p90_nll", "top10_mean_nll"]

rows = []

for feat in features:
    x = df[feat].values
    y = df["kstar"].values

    pearson_r, pearson_p = pearsonr(x, y)
    spearman_r, spearman_p = spearmanr(x, y)

    rows.append({
        "feature": feat,
        "pearson_r": pearson_r,
        "pearson_p": pearson_p,
        "spearman_r": spearman_r,
        "spearman_p": spearman_p
    })

corr_df = pd.DataFrame(rows)
corr_df

          feature  pearson_r  pearson_p  spearman_r  spearman_p
0        mean_nll   0.015544   0.878008    0.024115    0.811762
1         std_nll   0.158604   0.115004    0.200243    0.045767
2         max_nll   0.131910   0.190791    0.132600    0.188461
3      median_nll   0.024708   0.807225    0.032452    0.748572
4         p90_nll   0.131776   0.191246    0.165533    0.099786
5  top10_mean_nll   0.124325   0.217798    0.158037    0.116326

## Now based on human intuition with the same data

In [8]:
import pandas as pd

df_imgnet100_human = pd.read_csv("../data/human_evals/human_eval_strongerblur.csv")

print(df_imgnet100_human.shape)
df_imgnet100_human.head()

(100, 2)

  image_name  human_score
0   y0_0.png            4
1   y0_1.png            6
2  y0_10.png            8
3  y0_11.png            9
4  y0_12.png            7

In [9]:
kstar_labels = {
    "y0_0.png": 57,
    "y0_1.png": 46,
    "y0_2.png": 11,
    "y0_3.png": 42,
    "y0_4.png": 19,
    "y0_5.png": 30,
    "y0_6.png": 46,
    "y0_7.png": 38,
    "y0_8.png": 51,
    "y0_9.png": 28,
    "y0_10.png": 8,
    "y0_11.png": 31,
    "y0_12.png": 18,
    "y0_13.png": 24,
    "y0_14.png": 45,
    "y0_15.png": 36,
    "y0_16.png": 34,
    "y0_17.png": 53,
    "y0_18.png": 42,
    "y0_19.png": 53,
    "y0_20.png": 48,
    "y0_21.png": 45,
    "y0_22.png": 35,
    "y0_23.png": 35,
    "y0_24.png": 77,
    "y0_25.png": 5,
    "y0_26.png": 38,
    "y0_27.png": 30,
    "y0_28.png": 24,
    "y0_29.png": 21,
    "y0_30.png": 22,
    "y0_31.png": 8,
    "y0_32.png": 31,
    "y0_33.png": 34,
    "y0_34.png": 39,
    "y0_35.png": 14,
    "y0_36.png": 53,
    "y0_37.png": 5,
    "y0_38.png": 35,
    "y0_39.png": 33,
    "y0_40.png": 41,
    "y0_41.png": 34,
    "y0_42.png": 19,
    "y0_43.png": 34,
    "y0_44.png": 46,
    "y0_45.png": 17,
    "y0_46.png": 19,
    "y0_47.png": 51,
    "y0_48.png": 22,
    "y0_49.png": 51,
    "y0_50.png": 26,
    "y0_51.png": 15,
    "y0_52.png": 28,
    "y0_53.png": 51,
    "y0_54.png": 35,
    "y0_55.png": 29,
    "y0_56.png": 35,
    "y0_57.png": 72,
    "y0_58.png": 48,
    "y0_59.png": 24,
    "y0_60.png": 11,
    "y0_61.png": 34,
    "y0_62.png": 44,
    "y0_63.png": 44,
    "y0_64.png": 21,
    "y0_65.png": 48,
    "y0_66.png": 39,
    "y0_67.png": 36,
    "y0_68.png": 44,
    "y0_69.png": 5,
    "y0_70.png": 39,
    "y0_71.png": 39,
    "y0_72.png": 51,
    "y0_73.png": 32,
    "y0_74.png": 26,
    "y0_75.png": 35,
    "y0_76.png": 32,
    "y0_77.png": 23,
    "y0_78.png": 42,
    "y0_79.png": 51,
    "y0_80.png": 53,
    "y0_81.png": 35,
    "y0_82.png": 51,
    "y0_83.png": 53,
    "y0_84.png": 48,
    "y0_85.png": 42,
    "y0_86.png": 31,
    "y0_87.png": 41,
    "y0_88.png": 22,
    "y0_89.png": 34,
    "y0_90.png": 22,
    "y0_91.png": 11,
    "y0_92.png": 42,
    "y0_93.png": 26,
    "y0_94.png": 51,
    "y0_95.png": 45,
    "y0_96.png": 45,
    "y0_97.png": 41,
    "y0_98.png": 45,
    "y0_99.png": 5,
}

In [10]:
kstar_df = pd.DataFrame([
    {"image_name": k, "kstar": v}
    for k, v in kstar_labels.items()
])

kstar_df.head()

  image_name  kstar
0   y0_0.png     57
1   y0_1.png     46
2   y0_2.png     11
3   y0_3.png     42
4   y0_4.png     19

In [11]:
df_intuition = pd.merge(df_imgnet100_human, kstar_df, on="image_name")

print(df_intuition.shape)
df_intuition.head()

(100, 3)

  image_name  human_score  kstar
0   y0_0.png            4     57
1   y0_1.png            6     46
2  y0_10.png            8      8
3  y0_11.png            9     31
4  y0_12.png            7     18

In [12]:
from scipy.stats import pearsonr, spearmanr

pearson = pearsonr(df_intuition["human_score"], df_intuition["kstar"])
spearman = spearmanr(df_intuition["human_score"], df_intuition["kstar"])

print("Human score vs k*")
print(f" Pearson:  r={pearson.statistic:.4f}, p={pearson.pvalue:.4f}")
print(f" Spearman: r={spearman.statistic:.4f}, p={spearman.pvalue:.4f}")

Human score vs k*
 Pearson:  r=0.1396, p=0.1660
 Spearman: r=0.1535, p=0.1274

# GMM strong blur epsilon 0.3 k*

In [ ]:
from pathlib import Path

PROJECT_ROOT = Path("/path/Sample-Adaptive-Diffusion-Steps")

DDR_ROOT = PROJECT_ROOT / "external" / "ddrm"
REF_RUN_DIR = DDR_ROOT / "exp" / "image_samples" / "IMAGENET 100 STRONG BLUR EPS 0.3" / "run_imagenet100_k100_strongerblur"

eval_image_paths = sorted(list(REF_RUN_DIR.glob("y0_*.png")))

print("num eval degraded images:", len(eval_image_paths))
for p in eval_image_paths:
    print(p.name)

num eval degraded images: 100
y0_0.png
y0_1.png
y0_10.png
y0_11.png
y0_12.png
y0_13.png
y0_14.png
y0_15.png
y0_16.png
y0_17.png
y0_18.png
y0_19.png
y0_2.png
y0_20.png
y0_21.png
y0_22.png
y0_23.png
y0_24.png
y0_25.png
y0_26.png
y0_27.png
y0_28.png
y0_29.png
y0_3.png
y0_30.png
y0_31.png
y0_32.png
y0_33.png
y0_34.png
y0_35.png
y0_36.png
y0_37.png
y0_38.png
y0_39.png
y0_4.png
y0_40.png
y0_41.png
y0_42.png
y0_43.png
y0_44.png
y0_45.png
y0_46.png
y0_47.png
y0_48.png
y0_49.png
y0_5.png
y0_50.png
y0_51.png
y0_52.png
y0_53.png
y0_54.png
y0_55.png
y0_56.png
y0_57.png
y0_58.png
y0_59.png
y0_6.png
y0_60.png
y0_61.png
y0_62.png
y0_63.png
y0_64.png
y0_65.png
y0_66.png
y0_67.png
y0_68.png
y0_69.png
y0_7.png
y0_70.png
y0_71.png
y0_72.png
y0_73.png
y0_74.png
y0_75.png
y0_76.png
y0_77.png
y0_78.png
y0_79.png
y0_8.png
y0_80.png
y0_81.png
y0_82.png
y0_83.png
y0_84.png
y0_85.png
y0_86.png
y0_87.png
y0_88.png
y0_89.png
y0_9.png
y0_90.png
y0_91.png
y0_92.png
y0_93.png
y0_94.png
y0_95.png
y0_96.png
y0_97.png
y0_98.png
y0_99.png

In [9]:
kstar_labels = {
    "orig_0.png": 67,
    "orig_1.png": 53,
    "orig_2.png": 21,
    "orig_3.png": 51,
    "orig_4.png": 39,
    "orig_5.png": 34,
    "orig_6.png": 59,
    "orig_7.png": 56,
    "orig_8.png": 59,
    "orig_9.png": 48,
    "orig_10.png": 14,
    "orig_11.png": 38,
    "orig_12.png": 28,
    "orig_13.png": 36,
    "orig_14.png": 53,
    "orig_15.png": 53,
    "orig_16.png": 44,
    "orig_17.png": 63,
    "orig_18.png": 53,
    "orig_19.png": 57,
    "orig_20.png": 67,
    "orig_21.png": 56,
    "orig_22.png": 36,
    "orig_23.png": 53,
    "orig_24.png": 84,
    "orig_25.png": 7,
    "orig_26.png": 59,
    "orig_27.png": 45,
    "orig_28.png": 33,
    "orig_29.png": 25,
    "orig_30.png": 32,
    "orig_31.png": 15,
    "orig_32.png": 41,
    "orig_33.png": 56,
    "orig_34.png": 46,
    "orig_35.png": 22,
    "orig_36.png": 59,
    "orig_37.png": 7,
    "orig_38.png": 53,
    "orig_39.png": 45,
    "orig_40.png": 46,
    "orig_41.png": 42,
    "orig_42.png": 34,
    "orig_43.png": 45,
    "orig_44.png": 63,
    "orig_45.png": 32,
    "orig_46.png": 28,
    "orig_47.png": 59,
    "orig_48.png": 31,
    "orig_49.png": 53,
    "orig_50.png": 36,
    "orig_51.png": 22,
    "orig_52.png": 34,
    "orig_53.png": 72,
    "orig_54.png": 51,
    "orig_55.png": 44,
    "orig_56.png": 54,
    "orig_57.png": 82,
    "orig_58.png": 67,
    "orig_59.png": 31,
    "orig_60.png": 24,
    "orig_61.png": 42,
    "orig_62.png": 57,
    "orig_63.png": 51,
    "orig_64.png": 29,
    "orig_65.png": 68,
    "orig_66.png": 46,
    "orig_67.png": 48,
    "orig_68.png": 56,
    "orig_69.png": 5,
    "orig_70.png": 46,
    "orig_71.png": 48,
    "orig_72.png": 57,
    "orig_73.png": 46,
    "orig_74.png": 33,
    "orig_75.png": 44,
    "orig_76.png": 51,
    "orig_77.png": 33,
    "orig_78.png": 53,
    "orig_79.png": 57,
    "orig_80.png": 67,
    "orig_81.png": 55,
    "orig_82.png": 63,
    "orig_83.png": 67,
    "orig_84.png": 67,
    "orig_85.png": 54,
    "orig_86.png": 42,
    "orig_87.png": 41,
    "orig_88.png": 27,
    "orig_89.png": 51,
    "orig_90.png": 30,
    "orig_91.png": 13,
    "orig_92.png": 53,
    "orig_93.png": 40,
    "orig_94.png": 63,
    "orig_95.png": 53,
    "orig_96.png": 53,
    "orig_97.png": 48,
    "orig_98.png": 45,
    "orig_99.png": 9,
}

In [10]:
def load_grayscale_image(path, image_size=64):
    img = Image.open(path).convert("L")  # grayscale
    img = img.resize((image_size, image_size))
    arr = np.array(img).astype(np.float32) / 255.0
    return arr

def extract_patches(img, patch_size=8, stride=4):
    patches = []
    H, W = img.shape
    for i in range(0, H - patch_size + 1, stride):
        for j in range(0, W - patch_size + 1, stride):
            patch = img[i:i+patch_size, j:j+patch_size].reshape(-1)
            patches.append(patch)
    return np.array(patches, dtype=np.float32)

In [11]:
def image_complexity_nll(path, image_size=64, patch_size=8, stride=4):
    img = load_grayscale_image(path, image_size=image_size)
    patches = extract_patches(img, patch_size=patch_size, stride=stride)
    patches_scaled = scaler.transform(patches)

    log_probs = gmm.score_samples(patches_scaled)
    nll = -log_probs

    top_k = max(1, int(0.1 * len(nll)))
    sorted_nll = np.sort(nll)

    return {
        "mean_nll": float(np.mean(nll)),
        "std_nll": float(np.std(nll)),
        "max_nll": float(np.max(nll)),
        "median_nll": float(np.median(nll)),
        "p90_nll": float(np.percentile(nll, 90)),
        "top10_mean_nll": float(np.mean(sorted_nll[-top_k:])),
    }

In [12]:
import re
from PIL import Image
import numpy as np

def extract_image_idx(filename):
    # works for y0_0.png, orig_3.png, etc.
    m = re.search(r"_(\d+)\.png$", filename)
    if m is None:
        raise ValueError(f"Could not extract image index from {filename}")
    return int(m.group(1))

rows = []

for path in eval_image_paths:
    idx = extract_image_idx(path.name)
    orig_name = f"orig_{idx}.png"   # maps degraded image back to your k* labels

    stats = image_complexity_nll(path, image_size=64, patch_size=8, stride=4)

    rows.append({
        "image": path.name,          # now this will be y0_*.png
        "image_idx": idx,
        "mean_nll": stats["mean_nll"],
        "std_nll": stats["std_nll"],
        "max_nll": stats["max_nll"],
        "median_nll": stats["median_nll"],
        "p90_nll": stats["p90_nll"],
        "top10_mean_nll": stats["top10_mean_nll"],
        "kstar": kstar_labels[orig_name],
    })

rows

[{'image': 'y0_0.png',
  'image_idx': 0,
  'mean_nll': -35.569017511165704,
  'std_nll': 34.65413791549626,
  'max_nll': 46.27836157021355,
  'median_nll': -29.871644871531483,
  'p90_nll': 10.963242562606693,
  'top10_mean_nll': 20.20016604739192,
  'kstar': 67},
 {'image': 'y0_1.png',
  'image_idx': 1,
  'mean_nll': 2.891589812035385,
  'std_nll': 32.318491693319736,
  'max_nll': 56.369491039696456,
  'median_nll': 5.365288368014212,
  'p90_nll': 41.969183246834845,
  'top10_mean_nll': 48.257200757737884,
  'kstar': 53},
 {'image': 'y0_10.png',
  'image_idx': 10,
  'mean_nll': -12.3531355063228,
  'std_nll': 27.80920953656294,
  'max_nll': 60.33094912523994,
  'median_nll': -12.540016238924109,
  'p90_nll': 20.36824584342561,
  'top10_mean_nll': 39.61758641477962,
  'kstar': 14},
 {'image': 'y0_11.png',
  'image_idx': 11,
  'mean_nll': 1.5971006881020398,
  'std_nll': 26.7673124784685,
  'max_nll': 54.33923519058206,
  'median_nll': 2.325639649297352,
  'p90_nll': 28.970429633358357,
  'top10_mean_nll': 40.09712986128199,
  'kstar': 38},
 {'image': 'y0_12.png',
  'image_idx': 12,
  'mean_nll': 9.978365821075998,
  'std_nll': 24.192935792251454,
  'max_nll': 61.14903847375461,
  'median_nll': 9.53320556199286,
  'p90_nll': 44.915527562855516,
  'top10_mean_nll': 50.160387503835935,
  'kstar': 28},
 {'image': 'y0_13.png',
  'image_idx': 13,
  'mean_nll': -11.089703680971434,
  'std_nll': 40.621385995681315,
  'max_nll': 58.52436696119665,
  'median_nll': -2.287919676835725,
  'p90_nll': 36.15988405516575,
  'top10_mean_nll': 45.467715461484254,
  'kstar': 36},
 {'image': 'y0_14.png',
  'image_idx': 14,
  'mean_nll': -7.285421538413015,
  'std_nll': 36.450256294913075,
  'max_nll': 68.00347647077261,
  'median_nll': -2.0390327841506504,
  'p90_nll': 35.014411424225194,
  'top10_mean_nll': 44.2860260912451,
  'kstar': 53},
 {'image': 'y0_15.png',
  'image_idx': 15,
  'mean_nll': 18.552032824295214,
  'std_nll': 15.654329877064042,
  'max_nll': 55.66322916663178,
  'median_nll': 20.90804319623188,
  'p90_nll': 35.59316249253988,
  'top10_mean_nll': 41.47121687033268,
  'kstar': 53},
 {'image': 'y0_16.png',
  'image_idx': 16,
  'mean_nll': -9.931406613733854,
  'std_nll': 49.125002741827444,
  'max_nll': 77.14168597252235,
  'median_nll': -1.5847826270689218,
  'p90_nll': 51.21659397374959,
  'top10_mean_nll': 62.281199184156996,
  'kstar': 44},
 {'image': 'y0_17.png',
  'image_idx': 17,
  'mean_nll': -8.767659259814991,
  'std_nll': 24.578579279902634,
  'max_nll': 41.31331309981905,
  'median_nll': -8.91688202648748,
  'p90_nll': 22.157576966760136,
  'top10_mean_nll': 28.933796138541062,
  'kstar': 63},
 {'image': 'y0_18.png',
  'image_idx': 18,
  'mean_nll': -34.168468486990854,
  'std_nll': 37.434037609311915,
  'max_nll': 42.48896317850517,
  'median_nll': -26.583186883235665,
  'p90_nll': 14.08143453133747,
  'top10_mean_nll': 24.596531735629426,
  'kstar': 53},
 {'image': 'y0_19.png',
  'image_idx': 19,
  'mean_nll': -30.04754242264282,
  'std_nll': 38.17901971487822,
  'max_nll': 51.5605191646343,
  'median_nll': -28.042096161986127,
  'p90_nll': 21.019150893515924,
  'top10_mean_nll': 31.553630388875675,
  'kstar': 57},
 {'image': 'y0_2.png',
  'image_idx': 2,
  'mean_nll': -9.674577569164242,
  'std_nll': 24.036398771027013,
  'max_nll': 36.82222192594282,
  'median_nll': -8.926544418693945,
  'p90_nll': 19.96240402443157,
  'top10_mean_nll': 25.831681996430337,
  'kstar': 21},
 {'image': 'y0_20.png',
  'image_idx': 20,
  'mean_nll': 9.36257114374759,
  'std_nll': 37.74062048431519,
  'max_nll': 68.15014739846536,
  'median_nll': 18.452455192424257,
  'p90_nll': 44.634047377550814,
  'top10_mean_nll': 51.55095378804766,
  'kstar': 67},
 {'image': 'y0_21.png',
  'image_idx': 21,
  'mean_nll': 2.625019927797179,
  'std_nll': 28.88488042372136,
  'max_nll': 62.00875639661297,
  'median_nll': 6.487306924177516,
  'p90_nll': 36.81628532176914,
  'top10_mean_nll': 46.05800669121209,
  'kstar': 56},
 {'image': 'y0_22.png',
  'image_idx': 22,
  'mean_nll': -15.051535288202803,
  'std_nll': 35.03262931741087,
  'max_nll': 63.732613484213665,
  'median_nll': -12.117463635774016,
  'p90_nll': 27.80783908833601,
  'top10_mean_nll': 37.84244381478227,
  'kstar': 36},
 {'image': 'y0_23.png',
  'image_idx': 23,
  'mean_nll': 3.1663196428818874,
  'std_nll': 29.484279942316146,
  'max_nll': 67.19450165303154,
  'median_nll': 3.010196071466019,
  'p90_nll': 43.92025271886568,
  'top10_mean_nll': 50.81055255200449,
  'kstar': 53},
 {'image': 'y0_24.png',
  'image_idx': 24,
  'mean_nll': -31.688626398141945,
  'std_nll': 25.411419529788915,
  'max_nll': 33.777401775906256,
  'median_nll': -26.158357028820237,
  'p90_nll': 0.17713957621148377,
  'top10_mean_nll': 13.779472699599706,
  'kstar': 84},
 {'image': 'y0_25.png',
  'image_idx': 25,
  'mean_nll': -20.968478688803533,
  'std_nll': 22.4376737739283,
  'max_nll': 24.06401242135789,
  'median_nll': -15.702231267035302,
  'p90_nll': 4.256595936226225,
  'top10_mean_nll': 11.79618791751335,
  'kstar': 7},
 {'image': 'y0_26.png',
  'image_idx': 26,
  'mean_nll': 3.918649810527844,
  'std_nll': 33.94506198561439,
  'max_nll': 67.42676362089792,
  'median_nll': 4.253517840940077,
  'p90_nll': 47.5679564970459,
  'top10_mean_nll': 57.05970300975286,
  'kstar': 59},
 {'image': 'y0_27.png',
  'image_idx': 27,
  'mean_nll': -4.362747169989709,
  'std_nll': 30.259765913068758,
  'max_nll': 53.16030921483836,
  'median_nll': 2.3877304849741163,
  'p90_nll': 28.631626509667587,
  'top10_mean_nll': 39.73930178907171,
  'kstar': 45},
 {'image': 'y0_28.png',
  'image_idx': 28,
  'mean_nll': -4.455678594517713,
  'std_nll': 20.252608611389306,
  'max_nll': 43.456142574526986,
  'median_nll': -5.547518062447441,
  'p90_nll': 20.621514579854978,
  'top10_mean_nll': 30.445184686428934,
  'kstar': 33},
 {'image': 'y0_29.png',
  'image_idx': 29,
  'mean_nll': 7.502621011098392,
  'std_nll': 21.195870473627238,
  'max_nll': 48.65403238403321,
  'median_nll': 9.898882931032052,
  'p90_nll': 31.70940294778771,
  'top10_mean_nll': 35.670787374864915,
  'kstar': 25},
 {'image': 'y0_3.png',
  'image_idx': 3,
  'mean_nll': 6.066140246809797,
  'std_nll': 28.70027391848414,
  'max_nll': 59.175567264157266,
  'median_nll': 12.631083625632684,
  'p90_nll': 35.936828333402225,
  'top10_mean_nll': 46.81569840427548,
  'kstar': 51},
 {'image': 'y0_30.png',
  'image_idx': 30,
  'mean_nll': -3.5577447544118073,
  'std_nll': 28.646388376977473,
  'max_nll': 53.556309753322964,
  'median_nll': -3.481418096731459,
  'p90_nll': 29.84755094721666,
  'top10_mean_nll': 40.43862971894505,
  'kstar': 32},
 {'image': 'y0_31.png',
  'image_idx': 31,
  'mean_nll': -2.541437715384009,
  'std_nll': 27.73602931471443,
  'max_nll': 54.199011735462534,
  'median_nll': 5.394598450009664,
  'p90_nll': 25.808411677516787,
  'top10_mean_nll': 33.796206252565256,
  'kstar': 15},
 {'image': 'y0_32.png',
  'image_idx': 32,
  'mean_nll': 19.1888303513377,
  'std_nll': 18.687171516763396,
  'max_nll': 57.300549753090394,
  'median_nll': 21.60367689310671,
  'p90_nll': 39.24153345518466,
  'top10_mean_nll': 45.4607102584562,
  'kstar': 41},
 {'image': 'y0_33.png',
  'image_idx': 33,
  'mean_nll': -24.39517574284421,
  'std_nll': 36.78899758365284,
  'max_nll': 44.3267295020412,
  'median_nll': -11.709590453378546,
  'p90_nll': 15.945693853587683,
  'top10_mean_nll': 22.464290187102907,
  'kstar': 56},
 {'image': 'y0_34.png',
  'image_idx': 34,
  'mean_nll': 1.7357779154083315,
  'std_nll': 39.79566658313078,
  'max_nll': 88.3458746392126,
  'median_nll': 5.568834214234716,
  'p90_nll': 49.51184717047595,
  'top10_mean_nll': 63.77032830120783,
  'kstar': 46},
 {'image': 'y0_35.png',
  'image_idx': 35,
  'mean_nll': 0.1844105915192132,
  'std_nll': 24.638471133019802,
  'max_nll': 51.72149186704719,
  'median_nll': 4.76328436087904,
  'p90_nll': 26.101939879944624,
  'top10_mean_nll': 35.27137764127612,
  'kstar': 22},
 {'image': 'y0_36.png',
  'image_idx': 36,
  'mean_nll': 0.5064123547525003,
  'std_nll': 37.52604420852219,
  'max_nll': 75.80321050167633,
  'median_nll': 2.7407026137962434,
  'p90_nll': 49.27630555784552,
  'top10_mean_nll': 59.165381947020826,
  'kstar': 59},
 {'image': 'y0_37.png',
  'image_idx': 37,
  'mean_nll': -21.044187995044012,
  'std_nll': 27.872859289123372,
  'max_nll': 30.802008373210093,
  'median_nll': -22.709584100834185,
  'p90_nll': 18.299901862742193,
  'top10_mean_nll': 23.810530108329303,
  'kstar': 7},
 {'image': 'y0_38.png',
  'image_idx': 38,
  'mean_nll': 6.270015965698671,
  'std_nll': 28.330374852877505,
  'max_nll': 78.26005999928438,
  'median_nll': 9.736427196299783,
  'p90_nll': 41.89271105791835,
  'top10_mean_nll': 53.98514577331202,
  'kstar': 53},
 {'image': 'y0_39.png',
  'image_idx': 39,
  'mean_nll': -8.75189859795723,
  'std_nll': 35.93988924223231,
  'max_nll': 53.35813550265359,
  'median_nll': -0.5386594974713199,
  'p90_nll': 29.09945471704343,
  'top10_mean_nll': 38.23592803905174,
  'kstar': 45},
 {'image': 'y0_4.png',
  'image_idx': 4,
  'mean_nll': -16.556940447496817,
  'std_nll': 30.052984259453275,
  'max_nll': 34.08599537596425,
  'median_nll': -13.366831100569032,
  'p90_nll': 18.153134854708952,
  'top10_mean_nll': 24.241277239037547,
  'kstar': 39},
 {'image': 'y0_40.png',
  'image_idx': 40,
  'mean_nll': 27.212003500598463,
  'std_nll': 23.35079559803034,
  'max_nll': 68.25040963960515,
  'median_nll': 31.25496771202496,
  'p90_nll': 48.43252193035381,
  'top10_mean_nll': 55.89368598982125,
  'kstar': 46},
 {'image': 'y0_41.png',
  'image_idx': 41,
  'mean_nll': 2.826506396529634,
  'std_nll': 24.10109067991123,
  'max_nll': 69.34771676739193,
  'median_nll': 2.7302931195881897,
  'p90_nll': 31.254970909688222,
  'top10_mean_nll': 49.44612287560856,
  'kstar': 42},
 {'image': 'y0_42.png',
  'image_idx': 42,
  'mean_nll': 0.9187582550370778,
  'std_nll': 31.781395486997493,
  'max_nll': 87.55645205192083,
  'median_nll': 5.528762352693148,
  'p90_nll': 35.71587691568612,
  'top10_mean_nll': 49.228133424506495,
  'kstar': 34},
 {'image': 'y0_43.png',
  'image_idx': 43,
  'mean_nll': 13.709405876853427,
  'std_nll': 24.247555200232192,
  'max_nll': 70.24453651344254,
  'median_nll': 15.53326012585848,
  'p90_nll': 42.88608413771574,
  'top10_mean_nll': 53.42426104858032,
  'kstar': 45},
 {'image': 'y0_44.png',
  'image_idx': 44,
  'mean_nll': -7.2842311706116,
  'std_nll': 37.069818665306094,
  'max_nll': 50.546430325245204,
  'median_nll': 5.552990109058913,
  'p90_nll': 28.977944271997696,
  'top10_mean_nll': 37.06573171568722,
  'kstar': 63},
 {'image': 'y0_45.png',
  'image_idx': 45,
  'mean_nll': -18.925142814901314,
  'std_nll': 41.736428719866865,
  'max_nll': 60.30764732614889,
  'median_nll': -4.214716216852581,
  'p90_nll': 24.571702735674567,
  'top10_mean_nll': 36.77273564883067,
  'kstar': 32},
 {'image': 'y0_46.png',
  'image_idx': 46,
  'mean_nll': -28.642925094577876,
  'std_nll': 41.90643989968955,
  'max_nll': 45.55992807188745,
  'median_nll': -19.873240290997376,
  'p90_nll': 25.06241188562162,
  'top10_mean_nll': 33.651603119504664,
  'kstar': 28},
 {'image': 'y0_47.png',
  'image_idx': 47,
  'mean_nll': -17.761200807385922,
  'std_nll': 38.55375843289832,
  'max_nll': 48.84438655281885,
  'median_nll': -14.08486683445582,
  'p90_nll': 27.439712711753803,
  'top10_mean_nll': 36.793659578958575,
  'kstar': 59},
 {'image': 'y0_48.png',
  'image_idx': 48,
  'mean_nll': 2.250015808778761,
  'std_nll': 34.607069706987204,
  'max_nll': 77.8668181590391,
  'median_nll': 7.942903971366082,
  'p90_nll': 43.93237405954972,
  'top10_mean_nll': 56.38105788733556,
  'kstar': 31},
 {'image': 'y0_49.png',
  'image_idx': 49,
  'mean_nll': -6.735737313062868,
  'std_nll': 35.29020496790151,
  'max_nll': 52.72124028712217,
  'median_nll': 0.6726682090584388,
  'p90_nll': 34.67012256334386,
  'top10_mean_nll': 42.817951931236266,
  'kstar': 53},
 {'image': 'y0_5.png',
  'image_idx': 5,
  'mean_nll': -8.667311096656851,
  'std_nll': 43.12140707009997,
  'max_nll': 62.34228621556519,
  'median_nll': -0.028325009804689986,
  'p90_nll': 43.06752471564198,
  'top10_mean_nll': 50.22048574565229,
  'kstar': 34},
 {'image': 'y0_50.png',
  'image_idx': 50,
  'mean_nll': 5.408307605393123,
  'std_nll': 23.588848046132078,
  'max_nll': 60.13324833490529,
  'median_nll': 6.465532729721018,
  'p90_nll': 34.1832743459736,
  'top10_mean_nll': 44.77960384256563,
  'kstar': 36},
 {'image': 'y0_51.png',
  'image_idx': 51,
  'mean_nll': -17.741321032038538,
  'std_nll': 40.03537270929414,
  'max_nll': 53.46098408853115,
  'median_nll': -7.848809146781712,
  'p90_nll': 31.37172157402132,
  'top10_mean_nll': 41.24826880880202,
  'kstar': 22},
 {'image': 'y0_52.png',
  'image_idx': 52,
  'mean_nll': -16.384316668019395,
  'std_nll': 31.30417277871512,
  'max_nll': 56.10914631791012,
  'median_nll': -17.79022453622801,
  'p90_nll': 26.680026013106897,
  'top10_mean_nll': 39.19685879020777,
  'kstar': 34},
 {'image': 'y0_53.png',
  'image_idx': 53,
  'mean_nll': 9.865964751453653,
  'std_nll': 26.56071395336189,
  'max_nll': 67.67266217261474,
  'median_nll': 8.57698238108602,
  'p90_nll': 46.09813266236248,
  'top10_mean_nll': 52.579784839397846,
  'kstar': 72},
 {'image': 'y0_54.png',
  'image_idx': 54,
  'mean_nll': 0.9223822445254695,
  'std_nll': 25.63657734902432,
  'max_nll': 59.725498990597394,
  'median_nll': 2.7484405750040715,
  'p90_nll': 30.661351812284344,
  'top10_mean_nll': 41.82248033456085,
  'kstar': 51},
 {'image': 'y0_55.png',
  'image_idx': 55,
  'mean_nll': 5.304297630610656,
  'std_nll': 25.971266574965565,
  'max_nll': 68.71849409563848,
  'median_nll': 6.242747380152733,
  'p90_nll': 38.280676136453,
  'top10_mean_nll': 45.98750661267976,
  'kstar': 44},
 {'image': 'y0_56.png',
  'image_idx': 56,
  'mean_nll': -30.29666205203643,
  'std_nll': 36.12036380438014,
  'max_nll': 53.25580378101365,
  'median_nll': -33.110911684896294,
  'p90_nll': 20.657480888023862,
  'top10_mean_nll': 30.876093767737874,
  'kstar': 54},
 {'image': 'y0_57.png',
  'image_idx': 57,
  'mean_nll': -11.335839769982785,
  'std_nll': 35.254226264754884,
  'max_nll': 42.702503898822876,
  'median_nll': -5.976592019902221,
  'p90_nll': 27.771687636404533,
  'top10_mean_nll': 34.17453367334126,
  'kstar': 82},
 {'image': 'y0_58.png',
  'image_idx': 58,
  'mean_nll': -1.4452123718052952,
  'std_nll': 31.529270681861284,
  'max_nll': 71.34441060150597,
  'median_nll': -3.3188622748273415,
  'p90_nll': 40.80511715979569,
  'top10_mean_nll': 55.561637851940105,
  'kstar': 67},
 {'image': 'y0_59.png',
  'image_idx': 59,
  'mean_nll': -48.67609834423238,
  'std_nll': 39.083594724167305,
  'max_nll': 40.923492360976,
  'median_nll': -63.97393575410908,
  'p90_nll': 16.08368709844134,
  'top10_mean_nll': 24.231671312378783,
  'kstar': 31},
 {'image': 'y0_6.png',
  'image_idx': 6,
  'mean_nll': -47.233562662129,
  'std_nll': 37.601109166968705,
  'max_nll': 43.28416961750001,
  'median_nll': -65.38067706338339,
  'p90_nll': 14.329760003156746,
  'top10_mean_nll': 20.950732283175352,
  'kstar': 59},
 {'image': 'y0_60.png',
  'image_idx': 60,
  'mean_nll': -2.4125876857943784,
  'std_nll': 39.109064301651614,
  'max_nll': 56.35182446267388,
  'median_nll': 13.812382203934224,
  'p90_nll': 40.21724871064233,
  'top10_mean_nll': 45.84975487041534,
  'kstar': 24},
 {'image': 'y0_61.png',
  'image_idx': 61,
  'mean_nll': -26.752362601948764,
  'std_nll': 40.41441516623542,
  'max_nll': 55.70550496978362,
  'median_nll': -12.373429695027678,
  'p90_nll': 21.256992566128584,
  'top10_mean_nll': 35.186777045960376,
  'kstar': 42},
 {'image': 'y0_62.png',
  'image_idx': 62,
  'mean_nll': -22.935938146079636,
  'std_nll': 37.724576297632346,
  'max_nll': 43.35623658733969,
  'median_nll': -20.50051251622911,
  'p90_nll': 30.339900929127285,
  'top10_mean_nll': 35.81195610678636,
  'kstar': 57},
 {'image': 'y0_63.png',
  'image_idx': 63,
  'mean_nll': -14.903108700713394,
  'std_nll': 48.18573481100903,
  'max_nll': 62.4279481925707,
  'median_nll': -14.00219312070852,
  'p90_nll': 47.43941237413006,
  'top10_mean_nll': 55.18279697866557,
  'kstar': 51},
 {'image': 'y0_64.png',
  'image_idx': 64,
  'mean_nll': 13.146714707721772,
  'std_nll': 26.917308842504447,
  'max_nll': 61.39569836444608,
  'median_nll': 17.743372353692845,
  'p90_nll': 40.46782254290436,
  'top10_mean_nll': 46.26565545277411,
  'kstar': 29},
 {'image': 'y0_65.png',
  'image_idx': 65,
  'mean_nll': 17.02167354947984,
  'std_nll': 27.100037143554673,
  'max_nll': 69.1562976235738,
  'median_nll': 19.351394189672593,
  'p90_nll': 48.57296662735879,
  'top10_mean_nll': 56.77933202798254,
  'kstar': 68},
 {'image': 'y0_66.png',
  'image_idx': 66,
  'mean_nll': -9.516894180071379,
  'std_nll': 31.96737405135533,
  'max_nll': 51.79673898291072,
  'median_nll': -4.553956173192596,
  'p90_nll': 25.367314040316984,
  'top10_mean_nll': 34.59227289847207,
  'kstar': 46},
 {'image': 'y0_67.png',
  'image_idx': 67,
  'mean_nll': -31.66975021805768,
  'std_nll': 40.14185918370712,
  'max_nll': 50.42589932843887,
  'median_nll': -28.092915330877585,
  'p90_nll': 21.280432276054167,
  'top10_mean_nll': 32.014424511271436,
  'kstar': 48},
 {'image': 'y0_68.png',
  'image_idx': 68,
  'mean_nll': 1.1559156080710717,
  'std_nll': 21.851543050005834,
  'max_nll': 46.35976452158411,
  'median_nll': -0.46684016061362754,
  'p90_nll': 29.226033050288898,
  'top10_mean_nll': 39.36978348194368,
  'kstar': 56},
 {'image': 'y0_69.png',
  'image_idx': 69,
  'mean_nll': -40.80443976880991,
  'std_nll': 25.241330750496406,
  'max_nll': 25.2123269391888,
  'median_nll': -44.831602806636276,
  'p90_nll': -10.64313363566929,
  'top10_mean_nll': 3.6073107971433647,
  'kstar': 5},
 {'image': 'y0_7.png',
  'image_idx': 7,
  'mean_nll': -2.405707758787042,
  'std_nll': 24.936817905968322,
  'max_nll': 57.38049102385628,
  'median_nll': -3.2684939160263107,
  'p90_nll': 29.425688501092555,
  'top10_mean_nll': 38.997163831672346,
  'kstar': 56},
 {'image': 'y0_70.png',
  'image_idx': 70,
  'mean_nll': -13.670839727835451,
  'std_nll': 13.917395794037018,
  'max_nll': 16.779464221575953,
  'median_nll': -12.537998450114305,
  'p90_nll': 2.8801338262560323,
  'top10_mean_nll': 9.159013272171551,
  'kstar': 46},
 {'image': 'y0_71.png',
  'image_idx': 71,
  'mean_nll': 20.5238626305015,
  'std_nll': 22.057566860258603,
  'max_nll': 62.63179647715966,
  'median_nll': 22.62746332913221,
  'p90_nll': 45.567471545676824,
  'top10_mean_nll': 52.07508554767114,
  'kstar': 48},
 {'image': 'y0_72.png',
  'image_idx': 72,
  'mean_nll': -15.781315610779792,
  'std_nll': 41.278277501850475,
  'max_nll': 67.46677818132774,
  'median_nll': -12.645126534034452,
  'p90_nll': 35.6568062470535,
  'top10_mean_nll': 46.36180193622748,
  'kstar': 57},
 {'image': 'y0_73.png',
  'image_idx': 73,
  'mean_nll': -37.516792609621966,
  'std_nll': 36.5567911087807,
  'max_nll': 44.0998518947503,
  'median_nll': -49.0618435136475,
  'p90_nll': 15.734166128686194,
  'top10_mean_nll': 27.09897040107616,
  'kstar': 46},
 {'image': 'y0_74.png',
  'image_idx': 74,
  'mean_nll': -1.5987276817258818,
  'std_nll': 33.09930621046155,
  'max_nll': 54.074870465512845,
  'median_nll': 5.012909011653687,
  'p90_nll': 32.48932034759135,
  'top10_mean_nll': 39.20065789619085,
  'kstar': 33},
 {'image': 'y0_75.png',
  'image_idx': 75,
  'mean_nll': 3.7780876805461445,
  'std_nll': 30.691301403472128,
  'max_nll': 52.30795813640905,
  'median_nll': 9.191220194628245,
  'p90_nll': 40.57624036504622,
  'top10_mean_nll': 44.87999963999345,
  'kstar': 44},
 {'image': 'y0_76.png',
  'image_idx': 76,
  'mean_nll': 24.52458705291237,
  'std_nll': 26.23889193667743,
  'max_nll': 72.91612256837259,
  'median_nll': 28.455889172665827,
  'p90_nll': 57.04318484125138,
  'top10_mean_nll': 62.54604022272586,
  'kstar': 51},
 {'image': 'y0_77.png',
  'image_idx': 77,
  'mean_nll': -18.984309094307797,
  'std_nll': 47.18062790853814,

In [13]:
import pandas as pd

df = pd.DataFrame(rows).sort_values("image").reset_index(drop=True)
df.to_csv("gmm_results_imgnet100_strongerblur_eps0.3.csv", index=False)
print("saved gmm_results_imgnet100_strongerblur_eps0.3.csv")
df

saved gmm_results_imgnet100_strongerblur_eps0.3.csv

,image,image_idx,mean_nll,std_nll,max_nll,median_nll,p90_nll,top10_mean_nll,kstar
0,y0_0.png,0,-35.569018,34.654138,46.278362,-29.871645,10.963243,20.200166,67
1,y0_1.png,1,2.891590,32.318492,56.369491,5.365288,41.969183,48.257201,53
2,y0_10.png,10,-12.353136,27.809210,60.330949,-12.540016,20.368246,39.617586,14
3,y0_11.png,11,1.597101,26.767312,54.339235,2.325640,28.970430,40.097130,38
4,y0_12.png,12,9.978366,24.192936,61.149038,9.533206,44.915528,50.160388,28
...,...,...,...,...,...,...,...,...,...
95,y0_95.png,95,16.624096,28.544132,62.431881,22.529280,46.028165,53.421239,53
96,y0_96.png,96,-1.757263,41.749042,68.965516,10.728576,42.173386,49.726142,53
97,y0_97.png,97,6.486147,30.649733,70.172862,12.051853,38.844075,51.599652,48
98,y0_98.png,98,-3.902189,28.810399,58.050335,1.072423,28.299559,35.611122,45
99,y0_99.png,99,-0.464256,32.899658,61.120752,1.811348,42.934010,51.504386,9

In [14]:
from scipy.stats import pearsonr, spearmanr

features = ["mean_nll", "std_nll", "max_nll", "median_nll", "p90_nll", "top10_mean_nll"]

for feat in features:
    x = df[feat].values
    y = df["kstar"].values

    pearson_r, pearson_p = pearsonr(x, y)
    spearman_r, spearman_p = spearmanr(x, y)

    print(f"{feat} vs k*")
    print(f"  Pearson:  r={pearson_r:.4f}, p={pearson_p:.4f}")
    print(f"  Spearman: r={spearman_r:.4f}, p={spearman_p:.4f}")
    print()

mean_nll vs k*
  Pearson:  r=0.0830, p=0.4119
  Spearman: r=0.0781, p=0.4399

std_nll vs k*
  Pearson:  r=0.1291, p=0.2005
  Spearman: r=0.1550, p=0.1236

max_nll vs k*
  Pearson:  r=0.1913, p=0.0566
  Spearman: r=0.1621, p=0.1071

median_nll vs k*
  Pearson:  r=0.0863, p=0.3932
  Spearman: r=0.0789, p=0.4350

p90_nll vs k*
  Pearson:  r=0.1983, p=0.0479
  Spearman: r=0.1942, p=0.0529

top10_mean_nll vs k*
  Pearson:  r=0.1830, p=0.0684
  Spearman: r=0.1881, p=0.0609

In [15]:
import pandas as pd
from scipy.stats import pearsonr, spearmanr

features = ["mean_nll", "std_nll", "max_nll", "median_nll", "p90_nll", "top10_mean_nll"]

rows = []

for feat in features:
    x = df[feat].values
    y = df["kstar"].values

    pearson_r, pearson_p = pearsonr(x, y)
    spearman_r, spearman_p = spearmanr(x, y)

    rows.append({
        "feature": feat,
        "pearson_r": pearson_r,
        "pearson_p": pearson_p,
        "spearman_r": spearman_r,
        "spearman_p": spearman_p
    })

corr_df = pd.DataFrame(rows)
corr_df

          feature  pearson_r  pearson_p  spearman_r  spearman_p
0        mean_nll   0.082956   0.411905    0.078100    0.439902
1         std_nll   0.129095   0.200514    0.155010    0.123576
2         max_nll   0.191274   0.056607    0.162123    0.107065
3      median_nll   0.086308   0.393202    0.078935    0.435013
4         p90_nll   0.198312   0.047943    0.194186    0.052878
5  top10_mean_nll   0.182994   0.068402    0.188082    0.060939